### PR TITLE
Added support for Swift 4.2. Closes #58.

### LINKED ISSUE #58: Support for Swift 4.2
When is Swift 4.2 support coming? I can't build my app on Xcode 10 because of INSPhotoGallery.

### PR DESCRIPTION
**Pull request by spencerwhyte**

### CODE REVIEW

**Comment by tumispro** [comment]
Is it on a tag already? I can't seem to update to these changes.

**Comment by spencerwhyte** [comment]
A release hasn't been put out yet by the inspace-io folks.

In order to get this to work with Carthage I temporarily just created a 1.2.7 tag in my own repo (spencerwhyte/INSPhotoGallery) and pointed my Cartfile there for now.

**Comment by m1entus** [comment]
Released.

**Comment by spencerwhyte** [comment]
🎉

**Pull request merged**
